services:
  - docker

jobs:
  include:
    - stage: Static Analysis
      name: "Static Analysis"
      script:
        - shellcheck Dockerfile-assets/*.sh
        - shellcheck bin/*.sh
    - stage: Installs
      name: "Full Install"
      env:
        - TEST_GROUP=2-3-7
        - TEST_GROUP=2-3-7-p1
        - TEST_GROUP=2-3-7-p2
        - TEST_GROUP=2-3-7-p3
        - TEST_GROUP=2-3-7-p4
        - TEST_GROUP=2-4-0
        - TEST_GROUP=2-4-1
        - TEST_GROUP=2-4-2
        - TEST_GROUP=2-4-3
        - TEST_GROUP=2-4-4
        - TEST_GROUP=2-4-4-p1
        - TEST_GROUP=2-4-4-p2
        - TEST_GROUP=2-4-4-p3
        - TEST_GROUP=2-4-5
        - TEST_GROUP=2-4-5-p1
        - TEST_GROUP=2-4-4-p2
        - TEST_GROUP=2-4-6
        - TEST_GROUP=2-latest
      before_install:
        - travis_retry wget https://github.com/docker/compose/releases/download/v2.17.0/docker-compose-linux-x86_64
        - sudo mv docker-compose-linux-x86_64 /usr/libexec/docker/cli-plugins/docker-compose
        - sudo chmod +x /usr/libexec/docker/cli-plugins/docker-compose
        - docker --version && docker compose version
      script:
        - FULL_INSTALL=1 make $TEST_GROUP
        - docker exec mtest '/ampersand/command.sh' 'php bin/magento'
        - curl --head http://0.0.0.0:1234 | grep 200
    - script:
        - cd tests/Ampersand_HelloWorld
        - composer install --no-interaction -vvv
        - CURRENT_EXTENSION="." vendor/bin/mtest-make $TEST_GROUP
        - vendor/bin/mtest 'vendor/bin/phpunit -c /var/www/html/dev/tests/integration/phpunit.xml.dist --testsuite Integration --debug'
      name: "Partial Install for Integration Tests"

after_failure:
  - vendor/bin/mtest 'cat var/log/*.log'
  - vendor/bin/mtest 'cat dev/tests/integration/tmp/sandbox*/var/log/*.log'
  - docker exec mtest '/ampersand/command.sh' 'cat /var/www/html/var/log/*.log'
  - docker exec mtest '/ampersand/command.sh' 'cat /var/log/apache2/error.log'
  - docker exec mtest '/ampersand/command.sh' 'cat /var/log/apache2/access.log'
  - sleep 10
