version: '3'
services:
  magento:
    depends_on:
      - elasticsearch
      - mysql
    image: ampco/magento-docker-test-instance:latest
    #build:
    #  context: ./
    #  dockerfile: Dockerfile
    platform: linux/amd64
    container_name: mtest
    volumes:
      - "$CURRENT_EXTENSION:/current_extension/"
    healthcheck:
      test: [ "CMD", "mysql", "-hdatabase", "-e", "'select 1'" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 20s
    stdin_open: true
    working_dir: /var/www/html/
    links:
      - "mysql:database"
    ports:
      - "$MAGENTO_PORT:$MAGENTO_PORT"
    environment:
      - ELASTICSEARCH_OPTIONS=$ELASTICSEARCH_OPTIONS
      - MAGENTO_PORT=$MAGENTO_PORT
      - MAGE_VERSION=$MAGE_VERSION
      - FULL_INSTALL=$FULL_INSTALL
      - MYSQL_DATABASE=magento
      - PHP_VERSION=$PHP_VERSION
      - COMPOSER_VERSION=$COMPOSER_VERSION
      - COMPOSER_REQUIRE_EXTRA=$COMPOSER_REQUIRE_EXTRA
  elasticsearch:
    container_name: mtest-elasticsearch
    image: $ELASTICSEARCH_VERSION
    environment:
      - discovery.type=single-node
  mysql:
    container_name: mtest-mysql
    image: $MYSQL_VERSION
    platform: linux/amd64
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
